# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldqm_db', '0004_run_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VFAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChipID', models.CharField(default=b'0xdead', max_length=6)),
                ('Status', models.CharField(default=b'0', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='amc',
            name='Status',
            field=models.CharField(default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='geb',
            name='Status',
            field=models.CharField(default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='geb',
            name='vfats',
            field=models.ManyToManyField(to='ldqm_db.VFAT'),
        ),
    ]
