# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldqm_db', '0005_auto_20160209_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='HWstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HWID', models.CharField(max_length=30)),
                ('State', models.CharField(default=b'0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amcStates', models.ManyToManyField(related_name='amc_states', to='ldqm_db.HWstate')),
                ('gebStates', models.ManyToManyField(related_name='geb_states', to='ldqm_db.HWstate')),
                ('vfatStates', models.ManyToManyField(related_name='vfat_states', to='ldqm_db.HWstate')),
            ],
        ),
        migrations.RemoveField(
            model_name='amc',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='geb',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='vfat',
            name='Status',
        ),
        migrations.AddField(
            model_name='run',
            name='State',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ldqm_db.SystemState'),
        ),
    ]
