# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldqm_db', '0006_auto_20160209_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='vfat',
            name='Slot',
            field=models.PositiveSmallIntegerField(default=255),
        ),
    ]
